### ISSUE TITLE
NodeJS 6.9.0 error creating project

### ISSUE THREAD

**Issue by mavieth** [dutchwebworks/generator-dwwpugsite#1]
I use NVM (node version manager) and ran into this issue after using your generator.

`00:54 $ yo dwwpugsite

     _-----_     ╭─────────────────╮
    |       |    │  Welcome to the │
    |--(o)--|    │  Dutchwebworks  │
   `---------´   │     Pugsite     │
    ( _´U`_ )    │    generator    │
    /___A___\   /╰─────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What is the name of this project? ftor
? What is the project description?
? What is your name? Michael
? What is your e-mail address? mavieth@gmail.com
? What is the version of your app? 1.0.0
? Which buildtool would you like to use? Gulp

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/MichaelVieth/.nvm/versions/node/v6.9.0/lib/node_modules/generator-dwwpugsite/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/Users/MichaelVieth/.nvm/versions/node/v6.9.0/lib/node_modules/generator-dwwpugsite/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/MichaelVieth/.nvm/versions/node/v6.9.0/lib/node_modules/generator-dwwpugsite/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at child._createProjectFileSystem (/Users/MichaelVieth/.nvm/versions/node/v6.9.0/lib/node_modules/generator-dwwpugsite/app/index.js:26:11)
    at child.writing (/Users/MichaelVieth/.nvm/versions/node/v6.9.0/lib/node_modules/generator-dwwpugsite/app/index.js:108:8)
    at /Users/MichaelVieth/.nvm/versions/node/v6.9.0/lib/node_modules/generator-dwwpugsite/node_modules/yeoman-generator/lib/base.js:430:16
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)`

nvm --version: 0.32.1

node -v: v6.9.0

npm -v: 3.10.8

**Comment by dutchwebworks** [comment]
I fixed #1 it in the v2.0.2 release. Please update your local copy of this Yeomand generator by running `npm install -g generator-dwwpugsite` and check if it's version v2.0.2 by running `npm list -g --depth=0`.  

Otherwise uninstall it `npm uninstall -g generator-dwwpugsite` and re-install it `npm install -g generator-dwwpugsite`.
